name: Executar Testes

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Executar testes
      run: |
        pytest --cov=src --cov-report=term-missing --cov-report=xml -v
    
    - name: Upload cobertura
      uses: codecov/codecov-action@v3
      if: success()
      with:
        file: ./coverage.xml